version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    image: quay.io/chambridge/cost-metrics-aggregator
    container_name: aggregator
    ports:
      - "8080:8080"
    env_file:
      - ./db.env
    depends_on:
      - db
    networks:
      - cost-metrics-net

  db:
    image: postgres:16
    container_name: aggregator-db
    environment:
      - POSTGRES_USER=costmetrics
      - POSTGRES_PASSWORD=costmetrics
      - POSTGRES_DB=costmetrics
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - cost-metrics-net

volumes:
  postgres_data:

networks:
  cost-metrics-net:
    driver: bridge
