apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-metrics-aggregator
  namespace: cost-metrics
  labels:
    app: cost-metrics-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cost-metrics-aggregator
  template:
    metadata:
      labels:
        app: cost-metrics-aggregator
    spec:
      initContainers:
      - name: init-db
        image: quay.io/chambrid/cost-metrics-aggregator:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          migrate -path /app/migrations -database "$DATABASE_URL" up &&
          /app/scripts/create_partitions
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cost-metrics-db
              key: database-url
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      containers:
      - name: cost-metrics-aggregator
        image: quay.io/chambrid/cost-metrics-aggregator:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cost-metrics-db
              key: database-url
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
